"use client";
import Link from "next/link";


export default function WindEnergy() {
return (
<div className="p-6 bg-emerald-50 min-h-screen  text-left space-y-4">
<h1 className="text-4xl font-bold text-blue-600">Wind Energy</h1>


<h2 className="text-2xl font-semibold text-slate-900 mt-4">How Wind Energy Works</h2>
<p className="text-slate-700">
Wind energy is generated by converting the kinetic energy of moving air into electricity.
When wind blows, it turns the blades of a wind turbine. These blades are connected to a rotor
that spins a generator, producing electrical energy.
</p>
<h2 className="text-2xl font-semibold text-slate-900 mt-4">Benefits of Wind Energy</h2>
<p className="text-slate-700">
Wind energy is a clean, renewable resource that produces no emissions during operation.
It is one of the fastest-growing sources of electricity globally.
</p>


<ul className="list-disc ml-6 text-slate-700">
<li>No air pollution</li>
<li>Highly scalable through wind farms</li>
<li>Reduces dependence on fossil fuels</li>
<li>Affordable and increasingly efficient</li>
</ul>


<h2 className="text-2xl font-semibold text-slate-900 mt-4">How Individuals Can Support Wind Energy</h2>
<p className="text-slate-700">
Even if you can't install a wind turbine, you can support the wind industry by choosing green
energy plans, conserving energy, or supporting wind development policies.
</p>
<ul className="list-disc ml-6 text-slate-700">
<li>Choose renewable electricity providers</li>
<li>Support community wind initiatives</li>
<li>Reduce overall energy consumption</li>
</ul>


<h2 className="text-2xl font-semibold text-slate-900 mt-4">Learn More</h2>
<a
href="https://www.energy.gov/eere/wind/how-wind-energy-works"
target="_blank"
className="text-blue-700 underline"
>
U.S. Department of Energy – https://www.energy.gov/articles/how-wind-turbine-works
</a>
<br />
<Link
href="/green"
className="inline-block mt-6 px-4 py-2 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl"
>
Go Back
</Link>
</div>
);
}